### ISSUE TITLE
confused about the configurable refresh-rate unit

### ISSUE THREAD

**Issue by uxbenkel** [Eisa01/FreshRSS---Auto-Refresh-Extension#10]
there is no comment about the unit of configurable refresh-rate parameter. is it second,minute,or hour?

**Comment by Eisa01** [comment]
'refresh_rate' => 'Refresh rate in minutes',
there is a comment stating it is in minutes, let me know if that helps.

**Comment by uxbenkel** [comment]
thanks a lot，got it
